### PR TITLE
Update en_us.json

### PR DESCRIPTION
**Pull request by Brun333rp**
These are changes to the naming of certain blocks and items. If any of these changes don't suit your criteria, please advise me and I'll change or revert it back to original. Alternatively, you can simply close this if you don't like none of the proposed changes.

- Fixed several instances of grammar errors, mainly the order that some words were in certain strings;
- "Sand Layer" has been renamed to "Strange Sand Layer";
- "Ceramic Tile Blocks" have been renamed to "Ceramic Tiles", and "Ceramic Tile" has been renamed to "Ceramic Tile Paver". The reason is due to "Ceramic Tile" being a secondary crafting recipe resultant from the use of "Ceramic Tile Blocks" on a crafting grid. To simplify this, it's kinda like calling wool "Carpet Blocks" or planks "Pressure Plate Blocks", so because of that I've changed this;
- Alabaster and Porphyry blocks no longer have "Brick" on their name. They are now labeled: "Polished Alabaster/Porphyry", "Carved Alabaster/Porphyry", "Alabaster/Porphyry Tiles" and "Alabaster/Porphyry Pillar". This also applies to stairs, slabs and wall variants;
- All instances of the word "Gold" have been replaced with "Golden", for consistency with vanilla Minecraft naming of most gold-related items;
- Desert Armor sets are now properly named, no longer having the name of the material they are made of between parentheses;

### CODE REVIEW

**Comment by GirafiStudios** [comment]
Thanks for your efforts!
The following is as they should be for sure, so please undo (Have to talk to Shadowclaimer about the rest): 
Emmer Wheat
Shrubs
Ores
Mummy and Wanderer armor
Villagers

**Comment by Brun333rp** [comment]
done. but why not have a differentiation between both types of shrubs and atum ores?

**Comment by GirafiStudios** [comment]
Summary of changes needed (To keep it more simple):
- Re-add "Large" to Large Limestone Bricks
- Change Ceramic Tile to Ceramic Tile Paver
- Change Emmer Wheat to Emmer Ear (Thanks!)
- Also if you could re-add the Mummy and Wanderer armor changes, that would be great (Sorry for the confusion initially!)

**Comment by Brun333rp** [comment]
what if I change the ores to "Limestone (Type) Ore"?

**Comment by GirafiStudios** [comment]
No changes to the ores, thanks :) They´re named exactly how we want them to be named :)

**Comment by Brun333rp** [comment]
ok, I've done the requested changes. I've also changed the "Cracked Limestone Bricks" to "Cracked Large Limestone Bricks", or may I revert it back to original?

**Comment by GirafiStudios** [comment]
Leave Cracked Limestone Bricks as they were for now, thanks :)

**Pull request merged**
