### PR TITLE
Update en_us.json

### PR DESCRIPTION
**Pull request by sscards55**
Corrected Tefnut's name
Corrected Item names based on ownership rules

### CODE REVIEW

**Comment by GirafiStudios** [comment]
@Shadowclaimer, I'm pretty sure we looked up the gramatical rules for this, before Atum 2.0. As this was something I brought up too.
So I'll let you decide.

**Comment by GirafiStudios** [comment]
Obviously the Tefnut ones needs fixing though.

**Comment by Shadowclaimer** [comment]
We debated this and looked it up and settled on what we have now.

**Comment by GirafiStudios** [comment]
If you could change it to just contain the Tefnut fixes, that would be great :)

**Pull request merged**
