### PR TITLE
Tag all the artifacts

### PR DESCRIPTION
**Pull request by Quezler**
> I am writing this from the perspective of the Enigmatica 6 Expert modpack, which relies on automating godshards.

The "problem" is that the items that can be molten in the godforge can't easily (read: cleanly) be identified automatically.

Currently you'd either need:
a) an hardcoded list of all the (41?) items
b) a hardcoded list of all the godnames
c) checking for items with the `atum:tooltip` tag, ignoring the `atum:nebu_hammer` & including `_of_atem` and `_of_ra`
d) just brute forcing items by seeing which items are accepted via the top side of the godforge
e) keeping the items 100% separate from everything else in a closed loop (encouraged, but not my cup of tea)

Whilst this could be fixed on the modpack level by tagging the (41?) artifact items with `atum:artifact` it would be cleaner if the mod itself added (& maintained) the tags, and since atum 2 itself seems to be a fan of tagging (e.g. even the dirty & cleaned relics are tagged) i'd say this pull request has a pretty good shot.

I have tried to test this myself before making this pull request, but i ran into some issues:
- intelij was spitting out some 1.18 gradle issues, so fixing that to compile a jar for this just was unappealing
- opening the curseforge jar as a zip, inserting this file & rezipping as .jar wouldn't launch as forge either
- i suppose i could have created my own datapack with just this file to test co-installed, but that required research

From what i _do_ understand modifying just this file seems fine, though I am creating this as a draft in case I missed an item or have a typo in there somewhere, since I typed them over one-by-one from jei.

The modpack is 1.16 and it looks like the master branch is heading for a 1.18 release, so even if this does gets merged said pack will probably not be able to benefit from it, but if this ends up being merged into the mod it would be easy leverage to backport it into that pack via kubejs.

🥔

### CODE REVIEW

**Comment by GirafiStudios** [comment]
As this is set to be a draft, I can't accept it.
Would be happy to accept it, looks good (If all artifacts is Include, can't check properly as Im on my phone atm.)

**Comment by Quezler** [comment]
i believe you (as repository owner) have the option to toggle between draft & open, but it might not be on the phone interface/app, so allow me:

**Comment by Quezler** [comment]
lovely 👍 

(just to confirm, master branch is 1.18, and this won't make its way into 1.16? useful to know for that kubejs thing)

**Comment by GirafiStudios** [comment]
This branch is for 1.18 yes. Not close to being done at all though.
Feel free to make a PR to the 1.16 branch.

**Pull request merged**
