### PR TITLE
Create pt_br.json

### PR DESCRIPTION
**Pull request by Brun333rp**
Brazilian portuguese translations.

### CODE REVIEW

**Comment by Brun333rp** [comment]
the word "Atum" in portuguese is used to refer to tuna fish, so it could cause confusion. because of this, I've made a adaptation and changed it to "Áthum" to differentiate the dimension from the fish. is this allowed, or I need to keep the original name?

**Comment by GirafiStudios** [comment]
As Atum is the name of the mod & the dimension, it would make sense to keep it.
If there were referenced to the fish in Portugese, the first letter in Atum would not be capital :)

**Comment by Brun333rp** [comment]
ok then

**Comment by Brun333rp** [comment]
also, I know it doesn't makes reference to tuna fish, but it would still sound a little weird and could cause confusion. this is the why I've asked

**Comment by GirafiStudios** [comment]
Is this done yet? :)

**Comment by Brun333rp** [comment]
just gonna make sure of certain things and then I'll mark it as ready for review

**Comment by Brun333rp** [comment]
guess I took a bit of time, right? and seems like I forgot to change the deadwood curio display translation to be consistent with all the others

**Comment by GirafiStudios** [comment]
You´re fine :)
You can make another PR to fix that, if you want to :)

**Comment by Brun333rp** [comment]
gonna make then, it's a minor error but I will do

**Pull request merged**
